apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: wordpress-config
spec:
  groups:
    - name: wordpress
      title: Wordpress
      description: Wordpress 
      items:
        - name: wp-port
          title: wordpress port
          type: text
          value: "30888"
